In [82]:
import math
def NumDiv():
    n = float(input("Enter Numerator Value : "))
    d = float(input("Enter Denominator Value :"))
    try:
        x=round(n/d,2)
        print("Value after divison of {} by {} is {}".format(n,d,x))
    except ZeroDivisionError as zde:
        print(zde)
    except Exception as e:
        print(e)
    finally:
        print("Job Successfully exited")

NumDiv()

Enter Numerator Value 12
Enter Denominator Value 7


Value after divison of 12.0 by 7.0 is 1.71
Job Successfully exited


In [55]:
# 2. Implement a Python program to generate all sentences where subject is in ["Americans",
# "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]
# Output should come as below:
# Americans play Baseball.
# Americans play Cricket.
# Americans watch Baseball.
# Americans watch Cricket.
# Indians play Baseball.
# Indians play Cricket.
# Indians watch Baseball.
# Indians watch Cricket.

subjects=(["Americans","Indians"])
verbs=(["play","watch"])
objects=(["Baseball","Cricket"])

for x in subjects:
    for y in verbs:
        for z in objects:
            print(x, y, z)


Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [81]:
# Task 2:
# 1. Write a function so that the columns of the output matrix are powers of the input vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

# # help(np.column_stack)
# # help(np.vander)
# # def geoprog():
# # x = np.array((1, 2, 3, 5, 7, 11))
# # N = int(input("Enter Power Value for Progression"))
# # print(np.column_stack(pow(x,i) for i in range(N)))
# # print(np.vander(x, N, increasing=True))

import numpy as np
def vectorprog():
    x = np.array((1, 2, 3, 5, 7, 11))
    n = int(input("Enter Power Value for Progression : "))
    print(np.vander(x, n, increasing=True))

vectorprog()



Enter Power Value for Progression 5


[[    1     1     1     1     1]
 [    1     2     4     8    16]
 [    1     3     9    27    81]
 [    1     5    25   125   625]
 [    1     7    49   343  2401]
 [    1    11   121  1331 14641]]
